#  APP        
url=http://www.shopping.com/   
   
#  Selenium      
webdriver.chrome.driver=resources/chromedriver  
   
#  CUSTOMER      
   
customerId=12345  
customerUsername=steven  
customerPassword=password123